version: '3'

vars:
  UV: uv

tasks:
  install:
    desc: Create/update dev environment
    cmds:
      - '{{.UV}} sync --group dev'

  test:
    desc: Run tests
    cmds:
      - '{{.UV}} run pytest -v'

  lint:
    desc: Run linting with ruff
    cmds:
      - '{{.UV}} run ruff check .'

  lint:fix:
    desc: Run linting with auto-fix
    cmds:
      - '{{.UV}} run ruff check --fix .'

  format:
    desc: Format code with ruff
    cmds:
      - '{{.UV}} run ruff format .'

  format:check:
    desc: Check code formatting
    cmds:
      - '{{.UV}} run ruff format --check .'

  typecheck:
    desc: Run static type checking
    cmds:
      - '{{.UV}} run mypy trinnov_altitude'

  check:
    desc: Run all checks (lint + format + typecheck + test)
    cmds:
      - task: lint
      - task: format:check
      - task: typecheck
      - task: test

  build:
    desc: Build package
    cmds:
      - '{{.UV}} build'

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build dist *.egg-info
      - rm -rf .pytest_cache .ruff_cache .mypy_cache
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete

  dev:
    desc: Setup development environment
    cmds:
      - task: install
