version: '3'

vars:
  UV: uv

tasks:
  install:
    desc: Create/update dev environment
    cmds:
      - '{{.UV}} sync --group dev'

  test:
    desc: Run tests
    cmds:
      - '{{.UV}} run pytest -v'

  test:integration-real:
    desc: Run read-only real-device integration tests (manual opt-in)
    cmds:
      - echo "Running read-only real-device integration tests against ${TRINNOV_HOST:-unset}:${TRINNOV_PORT:-44100}"
      - test "${TRINNOV_ITEST:-}" = "1" || (echo "Set TRINNOV_ITEST=1 to enable real-device tests" && exit 1)
      - test -n "${TRINNOV_HOST:-}" || (echo "Set TRINNOV_HOST to your Altitude host/IP" && exit 1)
      - '{{.UV}} run pytest -v -m integration_real'

  lint:
    desc: Run linting with ruff
    cmds:
      - '{{.UV}} run ruff check .'

  lint:fix:
    desc: Run linting with auto-fix
    cmds:
      - '{{.UV}} run ruff check --fix .'

  format:
    desc: Format code with ruff
    cmds:
      - '{{.UV}} run ruff format .'

  format:check:
    desc: Check code formatting
    cmds:
      - '{{.UV}} run ruff format --check .'

  typecheck:
    desc: Run static type checking
    cmds:
      - '{{.UV}} run ty check trinnov_altitude'

  check:
    desc: Run all checks (lint + format + typecheck + test)
    cmds:
      - task: lint
      - task: format:check
      - task: typecheck
      - task: test

  build:
    desc: Build package
    cmds:
      - '{{.UV}} build'

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build dist *.egg-info
      - rm -rf .pytest_cache .ruff_cache .mypy_cache .ty_cache
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete

  dev:
    desc: Setup development environment
    cmds:
      - task: install
