version: '3'

vars:
  PYTHON: python3
  UV: uv

tasks:
  install:
    desc: Install dependencies
    cmds:
      - '{{.UV}} pip install -e .'
      - '{{.UV}} pip install -r requirements-dev.txt'

  test:
    desc: Run tests
    cmds:
      - pytest -v

  lint:
    desc: Run linting with ruff
    cmds:
      - '{{.UV}}x ruff check .'

  lint:fix:
    desc: Run linting with auto-fix
    cmds:
      - '{{.UV}}x ruff check --fix .'

  format:
    desc: Format code with ruff
    cmds:
      - '{{.UV}}x ruff format .'

  format:check:
    desc: Check code formatting
    cmds:
      - '{{.UV}}x ruff format --check .'

  check:
    desc: Run all checks (lint + format + test)
    cmds:
      - task: lint
      - task: format:check
      - task: test

  build:
    desc: Build package
    cmds:
      - '{{.PYTHON}} -m build'

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf build dist *.egg-info
      - rm -rf .pytest_cache .ruff_cache
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete

  dev:
    desc: Setup development environment
    cmds:
      - '{{.UV}} venv'
      - task: install
